CC=g++
#LINK=-lcreate -lboost_system -lboost_thread
SOURCE=main.cpp Search.cpp
OBJECT=main.o Search.o
TARGET=run_algo

all: $(TARGET)
clean:
	rm -f $(TARGET) $(OBJECT)

$(TARGET):
	$(CC) $(SOURCE) -o $(TARGET) 
#$(LINK)
